apiVersion: v1
kind: Service
metadata:
    name: "kubecluster-f2ce"
    labels:
        app: "kubecluster-f2ce"
spec:
    type: LoadBalancer
    ports:
    - port: 2222
      targetPort: 2222
      protocol: TCP
      name: http
    selector:
        app: "kubecluster-f2ce"